[package]
name = "aws_lc_repro"
version = "0.1.0"
edition = "2021"

[dependencies]
rustls = { version = "0.23", features = ["std", "prefer-post-quantum", "logging", "tls12"], default-features = false }
rustls-native-certs = "0.8"
